version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
     - PYTHONUNBUFFERED=0
    volumes:
     - .:/code

  redis:
    image: "whitewizardee/redis:alpine"
    command: redis-server --appendonly yes
    command: redis-server --save 60 5
    volumes:
     - ./backup:/data
