version: '2'
services:
  web:
    image: "whitewizardee/sessionpredictionapi_web:v3"
    ports:
     - "5000:5000"
    environment:
     - PYTHONUNBUFFERED=0
     - APP_URL_PREFIX=localhost
     - APP_PORT=5000

  redis:
    image: "whitewizardee/redis:alpine"
    command: redis-server --appendonly yes
    command: redis-server --save 60 5
    volumes:
     - ./backup:/data

